@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU2MDU0ODh9.A1XiYZibRMPxz6dsKa4hTmSTFw3zswuE55Y5jHr7Ny8


### Create User

  POST http://localhost:3000/users.json
  Content-Type: application/json

  {
  "email": "test@test.com",
  "username": "test_guy",
  "first_name": "Test", 
  "last_name": "Test", 
  "password": "password", 
  "password_confirmation": "password" 
  }

### User Index
  get http://localhost:3000/users
  Content-Type: application/json

### User Show
  get http://localhost:3000/users/1.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  
### User Login
  POST http://localhost:3000/sessions.json
  Content-Type: application/json

  {
  "email": "pjonasson@outlook.com",
  "password": "password"
  }


### Create Workout

  POST http://localhost:3000/workouts.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
  "number_of_lifts": 6
  }
### Lift_workout Index
  get http://localhost:3000/lift_workouts.json
  Content-Type: application/json

### Primary Muscle Index
  get http://localhost:3000/primary_muscles.json
  Content-Type: application/json


### Primary Muscle Show

  get http://localhost:3000/primary_muscles/1.json
  Content-Type: application/json

### Delete Workout
  delete http://localhost:3000/workouts/6
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

### Create Lift_workout
  post http://localhost:3000/lift_workouts
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
    "primary_muscle_id": 6,
    "workout_id": 4
  }

### Update Lift_workout
  patch http://localhost:3000/lift_workouts/10.json
  Content-Type: application/json
  Authorization: Bearer {{jwt}}

  {
    "weight1": 225,
    "weight2": 225,
    "set3_reps": 11,
    "weight3": 225,
    "comments": "Add more weight next time. Did an extra rep."
  }



  